### PR TITLE
serialization: fix Encoder.error pretending to be EmptyEncoder

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Comment by RainWarrior** [comment]
Hmm, not sure this is ready to merge yet, would like some more eyes on it. :P

**Comment by eatmyvenom** [comment]
Guys you can approve multiple times

**Comment by liach** [comment]
> 
> 
> Guys you can approve multiple times

No point to approve again before the pr has changed

**Comment by FinnT730** [comment]
Oh hey.... it is accepted! Thought we needed to ping everyone on all platforms to get 500K approvals
:P

**Pull request merged**
