### PR TITLE
Split up bootstrap tasks and submit individual ones to the executor.

### PR DESCRIPTION
**Pull request by RainWarrior**
Same as #28, but without manual task splitting, since the executor is doing that.

### CODE REVIEW

**Comment by aikar** [comment]
This bombards the process with hundreds of threads (I think I saw it go over 1k). That is why I did what I did in my PR.

MC is using a Cached Thread Pool. Unless you change that on MC, this is not good.

Now, overall I do prefer the cleaner approach here, but really needs clarity that it needs to use a queued executor instead.

**Comment by ichttt** [comment]
Can confirm, 1.13.2 pre 1 creates over 1000 threads at startup (for reference: 1.13.1 needs about 50). This really lags out some systems completly.

**Comment by LordRalex** [comment]
Just to mark this as a reference, this change introduced 2 bugs which will kill the game on old hardware (below minimum requirements, but generally dual cores with no SMT/HT available).

https://bugs.mojang.com/browse/MC-137353
https://bugs.mojang.com/browse/MC-138093

**Comment by winnipeg21** [comment]
When opening 1.13 my computer does 5fps causing other programs to also lag or crash.

**Pull request merged**
